### ISSUE TITLE
7.2.2 Fixing Leaks の日本語訳が入っていない

### ISSUE THREAD

**Issue by shino** [ymotongpoo/erlang-in-anger#53]
erlang-in-anger/107-memory-leaks-ja.tex at japanese · ymotongpoo/erlang-in-anger
https://github.com/ymotongpoo/erlang-in-anger/blob/japanese/107-memory-leaks-ja.tex#L223

けど google spread sheet では翻訳完了になっている。
どっちが正解でしょう?

**Comment by ymotongpoo** [comment]
僕が間違って変更してしまったのかもしれないです。

@mookjp ここお願いしてもよいでしょうか？

**Comment by mookjp** [comment]
@shino @ymotongpoo 確認します！もしかしたら私の翻訳漏れかもしれません。手元にdiffなかったら、別途作ってレビュー依頼しますー

**Comment by mookjp** [comment]
マージしたのでクローズします。
