### ISSUE TITLE
Travis CIのUbuntu18.04化に伴う秘密鍵更新

### ISSUE THREAD

**Issue by y-yu** [ymotongpoo/erlang-in-anger#66]
- Erlang in AngerのTravis CIまわりをアップデートしていたら、OpenSSLがUbuntu 18.04で1.1系となってしまって軽くしらべた限りではこれまでのオプションではPDFをプッシュする秘密鍵を復号できなくなってしまった 😇 
    - https://github.com/scalajp/scala_text_pdf/pull/5 👈 こういうことが必要

**Comment by y-yu** [comment]
- 調べたところ、僕はすでに`travis encrypt`でセキュア環境変数をつくれるので、公開鍵を登録してもらうだけでよさそう

**Comment by ymotongpoo** [comment]
お、こちらで何かしら公開鍵登録したほうがいいですか？それとも @y-yu さんのほうで対応される？

**Comment by y-yu** [comment]
@ymotongpoo 

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDPtY46uhLcn2YCkQmN7Sl1gqjjFQ352ZExCCBXuPCss9G3cT4fmsGN88fXN1TW+b3mOJv6LlpJF0dMcCYu1PgdFOWIblpgAd68bSTqyjST7bgjRYu6pCykFGJbL5WtkinSo+DzI+GYwaEI05d4NH7tzFuzNorQNiTpez/4Egx1zdRaoiO2y1j6815kaB3++7p3botuF3CN5kV8Boi5El3oIvNHVz4ji0qSJ4OfH4cq833vBEVWXV6wLFcExomvQoDexYtRxWw56e2Bgu+xKs2Xfrul2MDjzi88mavmGBSZJi74v9b6O2RZwZiKCmaKq6LANpgP3feC/xkvkWiq4L/9 yyu@fs276edb41.tkyc512.ap.nuro.jp
```

👆 こちらを公開鍵登録（writeあり）していただけると 🙇

**Comment by ymotongpoo** [comment]
@y-yu Deploy KeyにAllow Write Accessを付与して追加しました

**Comment by y-yu** [comment]
ありがとうございます！ #67 をマージして作業完了となりました。
