### ISSUE TITLE
"dash" character merging into the following character

### ISSUE THREAD

**Issue by sylph01** [ymotongpoo/erlang-in-anger#8]
横棒線が次の文字に食い込んで表示されているようです。例は以下:

<img width="1047" alt="2018-06-20 15 15 54" src="https://user-images.githubusercontent.com/809530/41640465-f224780c-749c-11e8-9e35-6d0cf259b431.png">

**Comment by ymotongpoo** [comment]
TeX関連なのでいったん @y-yu さんにAssignしましたが、致命傷なものではなく、ビルドに影響するものではないので nice to have で優先度は低めでokです。
